Added few comments on FSM of fetch buffer
Kaveesha-98/FYP-18-RISCV-Core pull request #13
Opened 2024-02-14 16:12 UTC by MCR748

2024-02-14 16:14 UTC, Kaveesha-98 commented
@TharukaN17 could you check whether the comments are correct?

2024-02-15 13:52 UTC, TharukaN17 requested changes

2024-02-15 13:52 UTC, TharukaN17 commented on src/main/scala/decode/decode.scala
> +      readyOutFetchBuf := true.B // -> Since FetchIssueBuffer is empty we can accept a new one
```suggestion
      readyOutFetchBuf := true.B // -> Since FetchIssueBuffer is empty, we can accept a new entry
```

2024-02-15 13:52 UTC, TharukaN17 commented on src/main/scala/decode/decode.scala
> +        // -> Accepting a new instruction from fetch
```suggestion
        // -> Accepting a new entry from fetch unit
```

2024-02-15 13:52 UTC, TharukaN17 commented on src/main/scala/decode/decode.scala
> +            // -> Not system stuff
```suggestion
            // -> Sending the entry to decodeIssueBuffer if it is not a system entry; otherwise, disregard it
```

2024-02-15 13:52 UTC, TharukaN17 commented on src/main/scala/decode/decode.scala
> +              // -> No new empty from Fetch
```suggestion
              // -> No new entry from fetch unit
```

2024-02-15 13:52 UTC, TharukaN17 commented on src/main/scala/decode/decode.scala
> +            // -> .Stall in issuing instruction in decodeIssueBuf
```suggestion
            // -> A stall in issuing the entry in decodeIssueBuf
```

2024-05-23 02:15 UTC, merged